version: "3.8"
services:
  consul:
    image: consul
    ports:
      - 8500:8500

  cart-service:
    image: chris/cart-service
    environment:
      CONSUL_HOST: consul
      ORDER_SERVICE_ADDRESS: http://order-service:8080
      SPRING_PROFILES_ACTIVE: consul
    ports:
      - 8001:8080
    # depends_on:
    #   - order-service

  order-service:
    image: chris/order-service
    environment:
      CONSUL_HOST: consul
    ports:
      - 8002:8080

  order-service-1:
    image: chris/order-service
    environment:
      CONSUL_HOST: consul

  order-service-2:
    image: chris/order-service
    environment:
      CONSUL_HOST: consul
